name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Snake

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: adit122022
          svg_path: assets/github-contribution-grid-snake.svg
        id: snake-gif

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'assets/github-contribution-grid-snake.svg'
          message: 'Update snake.svg'
