name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate GitHub Contribution Snake

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: adit122022
          outputs: |
            ./output/github-contribution-grid-snake.svg

      - name: Commit and push
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add output/github-contribution-grid-snake.svg
          git commit -m "Update contribution snake"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
