name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate GitHub Contribution Snake

    steps:
      - name: Generate the snake.svg file
        uses: Platane/snk@v3
        with:
          github_user_name: adit122022
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Setup Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Commit and Push the snake svg to main branch
        run: |
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update GitHub Contribution Snake"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
