name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Every midnight
  workflow_dispatch:

jobs:
  generate:
    name: Generate GitHub Contribution Snake
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: adit122022
          outputs: |
            ./output/github-contribution-grid-snake.svg

      - name: Push the SVG to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
